# Generated by Django 2.1.1 on 2018-10-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwordbook',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userwordbook',
            name='word_id',
        ),
        migrations.DeleteModel(
            name='UserWordbook',
        ),
    ]
