# Generated by Django 2.1.1 on 2018-10-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wordbook',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='単語ID')),
                ('word', models.CharField(max_length=150, verbose_name='単語')),
                ('word_class', models.CharField(blank=True, max_length=20, verbose_name='品詞')),
                ('word_meaning', models.TextField(verbose_name='意味')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'wordbook',
            },
        ),
    ]
