# Generated by Django 2.1.1 on 2018-10-24 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWordbook',
            fields=[
                ('user_wordbook', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ユーザー単語帳ID')),
                ('is_understood', models.BooleanField(default=False, verbose_name='ユーザー理解度')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='login_user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
            ],
            options={
                'db_table': 'user_wordbook',
            },
        ),
        migrations.CreateModel(
            name='Wordbook',
            fields=[
                ('word', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='単語ID')),
                ('vocabulary', models.CharField(max_length=150, verbose_name='単語')),
                ('word_class', models.CharField(blank=True, max_length=20, verbose_name='品詞')),
                ('word_meaning', models.TextField(verbose_name='意味')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'wordbook',
            },
        ),
        migrations.AddField(
            model_name='userwordbook',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wordbook.Wordbook', verbose_name='単語ID'),
        ),
    ]
