# Generated by Django 2.1.1 on 2018-10-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwordbook',
            name='word',
        ),
        migrations.AddField(
            model_name='userwordbook',
            name='word',
            field=models.ManyToManyField(blank=True, null=True, to='wordbook.Wordbook', verbose_name='単語ID'),
        ),
    ]
