# Generated by Django 2.1.1 on 2018-10-11 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wordbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWordbook',
            fields=[
                ('user_wordbook_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ユーザー単語帳ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordbook.Wordbook', verbose_name='単語ID')),
            ],
            options={
                'db_table': 'user_wordbook',
            },
        ),
    ]
