# Generated by Django 2.1.1 on 2018-10-22 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwordbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='login_user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
    ]
