# Generated by Django 2.1.1 on 2018-10-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordbook', '0002_userwordbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwordbook',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='userwordbook',
            old_name='word',
            new_name='word_id',
        ),
    ]
