# Generated by Django 2.1.1 on 2018-10-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbook', '0002_auto_20181015_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwordbook',
            name='understood_words',
            field=models.BooleanField(default=False, verbose_name='ユーザーの理解度判別'),
        ),
    ]
