# Generated by Django 2.1.1 on 2018-10-12 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordbook', '0003_auto_20181011_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwordbook',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wordbook', to=settings.AUTH_USER_MODEL),
        ),
    ]
