# Generated by Django 2.1.1 on 2018-10-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordbook', '0003_userwordbook_understood_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwordbook',
            name='understood_words',
        ),
        migrations.AddField(
            model_name='userwordbook',
            name='is_udnerstood',
            field=models.BooleanField(default=False, verbose_name='ユーザー理解度'),
        ),
    ]
