# Generated by Django 2.1.1 on 2018-10-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordbook', '0004_auto_20181019_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwordbook',
            old_name='is_udnerstood',
            new_name='is_underrstood',
        ),
    ]
