# Generated by Django 2.1.1 on 2018-10-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordbook', '0005_auto_20181021_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwordbook',
            old_name='is_underrstood',
            new_name='is_understood',
        ),
    ]
